development:
  dialect: "mysql"
  database: "cfbeirario_development"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"
  encoding: "utf8mb4_general_ci"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@(localhost:3306)/cfbeirario_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/cfbeirario_production?parseTime=true&multiStatements=true&readTimeout=1s"}}